// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Agent struct {
	ID             int64              `json:"id"`
	Uuid           uuid.UUID          `json:"uuid"`
	Role           string             `json:"role"`
	DisplayName    string             `json:"display_name"`
	Capabilities   []byte             `json:"capabilities"`
	CapabilityHash string             `json:"capability_hash"`
	Active         *bool              `json:"active"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type AuditLog struct {
	ID          int64              `json:"id"`
	ActorType   string             `json:"actor_type"`
	ActorID     *int64             `json:"actor_id"`
	EventType   string             `json:"event_type"`
	GoalID      *int64             `json:"goal_id"`
	PayloadJson []byte             `json:"payload_json"`
	PayloadHash *string            `json:"payload_hash"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type CriticIteration struct {
	ID                int64              `json:"id"`
	GoalID            int64              `json:"goal_id"`
	RoundNumber       int32              `json:"round_number"`
	ImplementerPrompt []byte             `json:"implementer_prompt"`
	ImplementerDiff   *string            `json:"implementer_diff"`
	SelfSatisfaction  pgtype.Numeric     `json:"self_satisfaction"`
	CriticPrompt      []byte             `json:"critic_prompt"`
	CriticFeedback    []byte             `json:"critic_feedback"`
	StartedAt         pgtype.Timestamptz `json:"started_at"`
	CompletedAt       *time.Time         `json:"completed_at"`
}

type Goal struct {
	ID                int64              `json:"id"`
	Uuid              uuid.UUID          `json:"uuid"`
	UserID            int64              `json:"user_id"`
	RepositoryID      *int64             `json:"repository_id"`
	Type              string             `json:"type"`
	Title             string             `json:"title"`
	Description       *string            `json:"description"`
	Status            string             `json:"status"`
	GithubPrNumber    *int32             `json:"github_pr_number"`
	GithubIssueNumber *int32             `json:"github_issue_number"`
	ForkMode          bool               `json:"fork_mode"`
	OutputJson        []byte             `json:"output_json"`
	Error             *string            `json:"error"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	CompletedAt       *time.Time         `json:"completed_at"`
	RepoFullName      *string            `json:"repo_full_name"`
}

type Installation struct {
	ID                   int64              `json:"id"`
	GithubInstallationID int64              `json:"github_installation_id"`
	AccountLogin         string             `json:"account_login"`
	AccountType          string             `json:"account_type"`
	InstalledByUserID    *int64             `json:"installed_by_user_id"`
	SuspendedAt          *time.Time         `json:"suspended_at"`
	InstalledAt          pgtype.Timestamptz `json:"installed_at"`
}

type Interrupt struct {
	ID          int64              `json:"id"`
	Uuid        uuid.UUID          `json:"uuid"`
	GoalID      int64              `json:"goal_id"`
	Type        string             `json:"type"`
	PayloadJson []byte             `json:"payload_json"`
	Decision    *string            `json:"decision"`
	Feedback    *string            `json:"feedback"`
	ActorUserID *int64             `json:"actor_user_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	ResolvedAt  *time.Time         `json:"resolved_at"`
}

type Message struct {
	ID           int64              `json:"id"`
	TaskID       int64              `json:"task_id"`
	Role         string             `json:"role"`
	Content      string             `json:"content"`
	ToolName     *string            `json:"tool_name"`
	ToolArgs     []byte             `json:"tool_args"`
	TokensIn     *int32             `json:"tokens_in"`
	TokensOut    *int32             `json:"tokens_out"`
	CachedTokens *int32             `json:"cached_tokens"`
	CostUsd      pgtype.Numeric     `json:"cost_usd"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Repository struct {
	ID             int64              `json:"id"`
	GithubRepoID   int64              `json:"github_repo_id"`
	FullName       string             `json:"full_name"`
	InstallationID *int64             `json:"installation_id"`
	DefaultBranch  string             `json:"default_branch"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Task struct {
	ID           int64      `json:"id"`
	Uuid         uuid.UUID  `json:"uuid"`
	GoalID       int64      `json:"goal_id"`
	AgentID      *int64     `json:"agent_id"`
	AgentRole    string     `json:"agent_role"`
	ToolName     *string    `json:"tool_name"`
	ArgsJson     []byte     `json:"args_json"`
	ArgsHash     *string    `json:"args_hash"`
	Status       string     `json:"status"`
	ResultJson   []byte     `json:"result_json"`
	ResultHash   *string    `json:"result_hash"`
	Error        *string    `json:"error"`
	AttemptCount *int32     `json:"attempt_count"`
	StartedAt    *time.Time `json:"started_at"`
	CompletedAt  *time.Time `json:"completed_at"`
}

type TaskDependency struct {
	TaskID      int64 `json:"task_id"`
	DependsOnID int64 `json:"depends_on_id"`
}

type User struct {
	ID                        int64              `json:"id"`
	Uuid                      uuid.UUID          `json:"uuid"`
	GithubID                  int64              `json:"github_id"`
	GithubLogin               string             `json:"github_login"`
	GithubOauthTokenEncrypted []byte             `json:"github_oauth_token_encrypted"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	LastLoginAt               *time.Time         `json:"last_login_at"`
}
