// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const createGoal = `-- name: CreateGoal :one
INSERT INTO goals (
    user_id, repo_full_name, type, title, description,
    github_pr_number, github_issue_number, fork_mode, status
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, 'pending')
RETURNING id, uuid, user_id, repository_id, type, title, description, status, github_pr_number, github_issue_number, fork_mode, output_json, error, created_at, updated_at, completed_at, repo_full_name
`

type CreateGoalParams struct {
	UserID            int64   `json:"user_id"`
	RepoFullName      *string `json:"repo_full_name"`
	Type              string  `json:"type"`
	Title             string  `json:"title"`
	Description       *string `json:"description"`
	GithubPrNumber    *int32  `json:"github_pr_number"`
	GithubIssueNumber *int32  `json:"github_issue_number"`
	ForkMode          bool    `json:"fork_mode"`
}

// ── Goals ─────────────────────────────────────────────────────────────────────
func (q *Queries) CreateGoal(ctx context.Context, arg CreateGoalParams) (Goal, error) {
	row := q.db.QueryRow(ctx, createGoal,
		arg.UserID,
		arg.RepoFullName,
		arg.Type,
		arg.Title,
		arg.Description,
		arg.GithubPrNumber,
		arg.GithubIssueNumber,
		arg.ForkMode,
	)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.UserID,
		&i.RepositoryID,
		&i.Type,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.GithubPrNumber,
		&i.GithubIssueNumber,
		&i.ForkMode,
		&i.OutputJson,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.RepoFullName,
	)
	return i, err
}

const createInterrupt = `-- name: CreateInterrupt :one
INSERT INTO interrupts (goal_id, type, payload_json)
VALUES ($1, $2, $3)
RETURNING id, uuid, goal_id, type, payload_json, decision, feedback, actor_user_id, created_at, resolved_at
`

type CreateInterruptParams struct {
	GoalID      int64  `json:"goal_id"`
	Type        string `json:"type"`
	PayloadJson []byte `json:"payload_json"`
}

// ── Interrupts (HITL gates) ───────────────────────────────────────────────────
func (q *Queries) CreateInterrupt(ctx context.Context, arg CreateInterruptParams) (Interrupt, error) {
	row := q.db.QueryRow(ctx, createInterrupt, arg.GoalID, arg.Type, arg.PayloadJson)
	var i Interrupt
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.GoalID,
		&i.Type,
		&i.PayloadJson,
		&i.Decision,
		&i.Feedback,
		&i.ActorUserID,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const getAgentByID = `-- name: GetAgentByID :one
SELECT id, uuid, role, display_name, capabilities, capability_hash, active, created_at FROM agents WHERE id = $1
`

// ── Agents (capability check) ─────────────────────────────────────────────────
func (q *Queries) GetAgentByID(ctx context.Context, id int64) (Agent, error) {
	row := q.db.QueryRow(ctx, getAgentByID, id)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Role,
		&i.DisplayName,
		&i.Capabilities,
		&i.CapabilityHash,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const getGoalByUUID = `-- name: GetGoalByUUID :one
SELECT id, uuid, user_id, repository_id, type, title, description, status, github_pr_number, github_issue_number, fork_mode, output_json, error, created_at, updated_at, completed_at, repo_full_name FROM goals WHERE uuid = $1
`

func (q *Queries) GetGoalByUUID(ctx context.Context, argUuid uuid.UUID) (Goal, error) {
	row := q.db.QueryRow(ctx, getGoalByUUID, argUuid)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.UserID,
		&i.RepositoryID,
		&i.Type,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.GithubPrNumber,
		&i.GithubIssueNumber,
		&i.ForkMode,
		&i.OutputJson,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.RepoFullName,
	)
	return i, err
}

const getPendingInterrupt = `-- name: GetPendingInterrupt :one
SELECT id, uuid, goal_id, type, payload_json, decision, feedback, actor_user_id, created_at, resolved_at FROM interrupts
WHERE goal_id = $1 AND resolved_at IS NULL
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetPendingInterrupt(ctx context.Context, goalID int64) (Interrupt, error) {
	row := q.db.QueryRow(ctx, getPendingInterrupt, goalID)
	var i Interrupt
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.GoalID,
		&i.Type,
		&i.PayloadJson,
		&i.Decision,
		&i.Feedback,
		&i.ActorUserID,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const getRepositoryByFullName = `-- name: GetRepositoryByFullName :one
SELECT id, github_repo_id, full_name, installation_id, default_branch, created_at FROM repositories WHERE full_name = $1
`

func (q *Queries) GetRepositoryByFullName(ctx context.Context, fullName string) (Repository, error) {
	row := q.db.QueryRow(ctx, getRepositoryByFullName, fullName)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.GithubRepoID,
		&i.FullName,
		&i.InstallationID,
		&i.DefaultBranch,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByGithubID = `-- name: GetUserByGithubID :one
SELECT id, uuid, github_id, github_login, github_oauth_token_encrypted, created_at, last_login_at FROM users WHERE github_id = $1
`

func (q *Queries) GetUserByGithubID(ctx context.Context, githubID int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByGithubID, githubID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.GithubID,
		&i.GithubLogin,
		&i.GithubOauthTokenEncrypted,
		&i.CreatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, uuid, github_id, github_login, github_oauth_token_encrypted, created_at, last_login_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.GithubID,
		&i.GithubLogin,
		&i.GithubOauthTokenEncrypted,
		&i.CreatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const getUserByUUID = `-- name: GetUserByUUID :one
SELECT id, uuid, github_id, github_login, github_oauth_token_encrypted, created_at, last_login_at FROM users WHERE uuid = $1
`

func (q *Queries) GetUserByUUID(ctx context.Context, argUuid uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUUID, argUuid)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.GithubID,
		&i.GithubLogin,
		&i.GithubOauthTokenEncrypted,
		&i.CreatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const getUserOAuthToken = `-- name: GetUserOAuthToken :one
SELECT github_login, github_oauth_token_encrypted
FROM users WHERE id = $1
`

type GetUserOAuthTokenRow struct {
	GithubLogin               string `json:"github_login"`
	GithubOauthTokenEncrypted []byte `json:"github_oauth_token_encrypted"`
}

func (q *Queries) GetUserOAuthToken(ctx context.Context, id int64) (GetUserOAuthTokenRow, error) {
	row := q.db.QueryRow(ctx, getUserOAuthToken, id)
	var i GetUserOAuthTokenRow
	err := row.Scan(&i.GithubLogin, &i.GithubOauthTokenEncrypted)
	return i, err
}

const goalCostBreakdown = `-- name: GoalCostBreakdown :many
SELECT
    t.agent_role,
    COUNT(*) FILTER (WHERE m.role = 'assistant')        AS call_count,
    COALESCE(SUM(m.tokens_in), 0)::bigint               AS tokens_in,
    COALESCE(SUM(m.tokens_out), 0)::bigint              AS tokens_out,
    COALESCE(SUM(m.cached_tokens), 0)::bigint           AS cached_tokens,
    COALESCE(ROUND(SUM(m.cost_usd), 6), 0)::float8      AS cost_usd
FROM messages m
JOIN tasks t ON m.task_id = t.id
WHERE t.goal_id = $1
GROUP BY t.agent_role
ORDER BY cost_usd DESC
`

type GoalCostBreakdownRow struct {
	AgentRole    string  `json:"agent_role"`
	CallCount    int64   `json:"call_count"`
	TokensIn     int64   `json:"tokens_in"`
	TokensOut    int64   `json:"tokens_out"`
	CachedTokens int64   `json:"cached_tokens"`
	CostUsd      float64 `json:"cost_usd"`
}

// ── Cost breakdown (per-role aggregation for a goal) ──────────────────────────
func (q *Queries) GoalCostBreakdown(ctx context.Context, goalID int64) ([]GoalCostBreakdownRow, error) {
	rows, err := q.db.Query(ctx, goalCostBreakdown, goalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GoalCostBreakdownRow
	for rows.Next() {
		var i GoalCostBreakdownRow
		if err := rows.Scan(
			&i.AgentRole,
			&i.CallCount,
			&i.TokensIn,
			&i.TokensOut,
			&i.CachedTokens,
			&i.CostUsd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertAuditLog = `-- name: InsertAuditLog :one
INSERT INTO audit_log (actor_type, actor_id, event_type, goal_id, payload_json, payload_hash)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, actor_type, actor_id, event_type, goal_id, payload_json, payload_hash, created_at
`

type InsertAuditLogParams struct {
	ActorType   string  `json:"actor_type"`
	ActorID     *int64  `json:"actor_id"`
	EventType   string  `json:"event_type"`
	GoalID      *int64  `json:"goal_id"`
	PayloadJson []byte  `json:"payload_json"`
	PayloadHash *string `json:"payload_hash"`
}

// ── Audit log ─────────────────────────────────────────────────────────────────
func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, insertAuditLog,
		arg.ActorType,
		arg.ActorID,
		arg.EventType,
		arg.GoalID,
		arg.PayloadJson,
		arg.PayloadHash,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.ActorType,
		&i.ActorID,
		&i.EventType,
		&i.GoalID,
		&i.PayloadJson,
		&i.PayloadHash,
		&i.CreatedAt,
	)
	return i, err
}

const listCriticIterationsByGoal = `-- name: ListCriticIterationsByGoal :many
SELECT id, goal_id, round_number, implementer_prompt, implementer_diff, self_satisfaction, critic_prompt, critic_feedback, started_at, completed_at FROM critic_iterations
WHERE goal_id = $1
ORDER BY round_number
`

// ── Critic iterations (Flow B transcript) ─────────────────────────────────────
func (q *Queries) ListCriticIterationsByGoal(ctx context.Context, goalID int64) ([]CriticIteration, error) {
	rows, err := q.db.Query(ctx, listCriticIterationsByGoal, goalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CriticIteration
	for rows.Next() {
		var i CriticIteration
		if err := rows.Scan(
			&i.ID,
			&i.GoalID,
			&i.RoundNumber,
			&i.ImplementerPrompt,
			&i.ImplementerDiff,
			&i.SelfSatisfaction,
			&i.CriticPrompt,
			&i.CriticFeedback,
			&i.StartedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGoalsByUser = `-- name: ListGoalsByUser :many
SELECT id, uuid, user_id, repository_id, type, title, description, status, github_pr_number, github_issue_number, fork_mode, output_json, error, created_at, updated_at, completed_at, repo_full_name FROM goals
WHERE user_id = $1
  AND ($4::text IS NULL OR status = $4)
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListGoalsByUserParams struct {
	UserID int64   `json:"user_id"`
	Limit  int32   `json:"limit"`
	Offset int32   `json:"offset"`
	Status *string `json:"status"`
}

func (q *Queries) ListGoalsByUser(ctx context.Context, arg ListGoalsByUserParams) ([]Goal, error) {
	rows, err := q.db.Query(ctx, listGoalsByUser,
		arg.UserID,
		arg.Limit,
		arg.Offset,
		arg.Status,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Goal
	for rows.Next() {
		var i Goal
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.UserID,
			&i.RepositoryID,
			&i.Type,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.GithubPrNumber,
			&i.GithubIssueNumber,
			&i.ForkMode,
			&i.OutputJson,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.RepoFullName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInterruptsByGoal = `-- name: ListInterruptsByGoal :many
SELECT id, uuid, goal_id, type, payload_json, decision, feedback, actor_user_id, created_at, resolved_at FROM interrupts WHERE goal_id = $1 ORDER BY created_at
`

func (q *Queries) ListInterruptsByGoal(ctx context.Context, goalID int64) ([]Interrupt, error) {
	rows, err := q.db.Query(ctx, listInterruptsByGoal, goalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Interrupt
	for rows.Next() {
		var i Interrupt
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.GoalID,
			&i.Type,
			&i.PayloadJson,
			&i.Decision,
			&i.Feedback,
			&i.ActorUserID,
			&i.CreatedAt,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByGoal = `-- name: ListTasksByGoal :many
SELECT id, uuid, goal_id, agent_id, agent_role, tool_name, args_json, args_hash, status, result_json, result_hash, error, attempt_count, started_at, completed_at FROM tasks WHERE goal_id = $1 ORDER BY id
`

// ── Tasks (read for goal detail) ──────────────────────────────────────────────
func (q *Queries) ListTasksByGoal(ctx context.Context, goalID int64) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasksByGoal, goalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.GoalID,
			&i.AgentID,
			&i.AgentRole,
			&i.ToolName,
			&i.ArgsJson,
			&i.ArgsHash,
			&i.Status,
			&i.ResultJson,
			&i.ResultHash,
			&i.Error,
			&i.AttemptCount,
			&i.StartedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveInterrupt = `-- name: ResolveInterrupt :exec
UPDATE interrupts
SET decision = $2, feedback = $3, actor_user_id = $4, resolved_at = NOW()
WHERE id = $1
`

type ResolveInterruptParams struct {
	ID          int64   `json:"id"`
	Decision    *string `json:"decision"`
	Feedback    *string `json:"feedback"`
	ActorUserID *int64  `json:"actor_user_id"`
}

func (q *Queries) ResolveInterrupt(ctx context.Context, arg ResolveInterruptParams) error {
	_, err := q.db.Exec(ctx, resolveInterrupt,
		arg.ID,
		arg.Decision,
		arg.Feedback,
		arg.ActorUserID,
	)
	return err
}

const updateGoalStatus = `-- name: UpdateGoalStatus :exec
UPDATE goals
SET status = $2,
    updated_at = NOW(),
    completed_at = CASE WHEN $2 IN ('done','failed','cancelled') THEN NOW() ELSE completed_at END
WHERE uuid = $1
`

type UpdateGoalStatusParams struct {
	Uuid   uuid.UUID `json:"uuid"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateGoalStatus(ctx context.Context, arg UpdateGoalStatusParams) error {
	_, err := q.db.Exec(ctx, updateGoalStatus, arg.Uuid, arg.Status)
	return err
}

const upsertRepository = `-- name: UpsertRepository :one
INSERT INTO repositories (github_repo_id, full_name, installation_id, default_branch)
VALUES ($1, $2, $3, $4)
ON CONFLICT (github_repo_id) DO UPDATE
  SET full_name = EXCLUDED.full_name,
      installation_id = EXCLUDED.installation_id,
      default_branch = EXCLUDED.default_branch
RETURNING id, github_repo_id, full_name, installation_id, default_branch, created_at
`

type UpsertRepositoryParams struct {
	GithubRepoID   int64  `json:"github_repo_id"`
	FullName       string `json:"full_name"`
	InstallationID *int64 `json:"installation_id"`
	DefaultBranch  string `json:"default_branch"`
}

// ── Repositories ──────────────────────────────────────────────────────────────
func (q *Queries) UpsertRepository(ctx context.Context, arg UpsertRepositoryParams) (Repository, error) {
	row := q.db.QueryRow(ctx, upsertRepository,
		arg.GithubRepoID,
		arg.FullName,
		arg.InstallationID,
		arg.DefaultBranch,
	)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.GithubRepoID,
		&i.FullName,
		&i.InstallationID,
		&i.DefaultBranch,
		&i.CreatedAt,
	)
	return i, err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (github_id, github_login, github_oauth_token_encrypted, last_login_at)
VALUES ($1, $2, $3, NOW())
ON CONFLICT (github_id) DO UPDATE
  SET github_login = EXCLUDED.github_login,
      github_oauth_token_encrypted = EXCLUDED.github_oauth_token_encrypted,
      last_login_at = NOW()
RETURNING id, uuid, github_id, github_login, github_oauth_token_encrypted, created_at, last_login_at
`

type UpsertUserParams struct {
	GithubID                  int64  `json:"github_id"`
	GithubLogin               string `json:"github_login"`
	GithubOauthTokenEncrypted []byte `json:"github_oauth_token_encrypted"`
}

// ── Users ─────────────────────────────────────────────────────────────────────
func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUser, arg.GithubID, arg.GithubLogin, arg.GithubOauthTokenEncrypted)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.GithubID,
		&i.GithubLogin,
		&i.GithubOauthTokenEncrypted,
		&i.CreatedAt,
		&i.LastLoginAt,
	)
	return i, err
}
