// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	// ── Goals ─────────────────────────────────────────────────────────────────────
	CreateGoal(ctx context.Context, arg CreateGoalParams) (Goal, error)
	// ── Interrupts (HITL gates) ───────────────────────────────────────────────────
	CreateInterrupt(ctx context.Context, arg CreateInterruptParams) (Interrupt, error)
	// ── Agents (capability check) ─────────────────────────────────────────────────
	GetAgentByID(ctx context.Context, id int64) (Agent, error)
	GetGoalByUUID(ctx context.Context, argUuid uuid.UUID) (Goal, error)
	GetPendingInterrupt(ctx context.Context, goalID int64) (Interrupt, error)
	GetRepositoryByFullName(ctx context.Context, fullName string) (Repository, error)
	GetUserByGithubID(ctx context.Context, githubID int64) (User, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	GetUserByUUID(ctx context.Context, argUuid uuid.UUID) (User, error)
	GetUserOAuthToken(ctx context.Context, id int64) (GetUserOAuthTokenRow, error)
	// ── Cost breakdown (per-role aggregation for a goal) ──────────────────────────
	GoalCostBreakdown(ctx context.Context, goalID int64) ([]GoalCostBreakdownRow, error)
	// ── Audit log ─────────────────────────────────────────────────────────────────
	InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) (AuditLog, error)
	// ── Critic iterations (Flow B transcript) ─────────────────────────────────────
	ListCriticIterationsByGoal(ctx context.Context, goalID int64) ([]CriticIteration, error)
	ListGoalsByUser(ctx context.Context, arg ListGoalsByUserParams) ([]Goal, error)
	ListInterruptsByGoal(ctx context.Context, goalID int64) ([]Interrupt, error)
	// ── Tasks (read for goal detail) ──────────────────────────────────────────────
	ListTasksByGoal(ctx context.Context, goalID int64) ([]Task, error)
	ResolveInterrupt(ctx context.Context, arg ResolveInterruptParams) error
	UpdateGoalStatus(ctx context.Context, arg UpdateGoalStatusParams) error
	// ── Repositories ──────────────────────────────────────────────────────────────
	UpsertRepository(ctx context.Context, arg UpsertRepositoryParams) (Repository, error)
	// ── Users ─────────────────────────────────────────────────────────────────────
	UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
