// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: orchestration.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ── Orchestration messages ────────────────────────────────────────────────────
type SubmitGoalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GoalUuid      string                 `protobuf:"bytes,1,opt,name=goal_uuid,json=goalUuid,proto3" json:"goal_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitGoalRequest) Reset() {
	*x = SubmitGoalRequest{}
	mi := &file_orchestration_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitGoalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitGoalRequest) ProtoMessage() {}

func (x *SubmitGoalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestration_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitGoalRequest.ProtoReflect.Descriptor instead.
func (*SubmitGoalRequest) Descriptor() ([]byte, []int) {
	return file_orchestration_proto_rawDescGZIP(), []int{0}
}

func (x *SubmitGoalRequest) GetGoalUuid() string {
	if x != nil {
		return x.GoalUuid
	}
	return ""
}

type SubmitGoalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitGoalResponse) Reset() {
	*x = SubmitGoalResponse{}
	mi := &file_orchestration_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitGoalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitGoalResponse) ProtoMessage() {}

func (x *SubmitGoalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestration_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitGoalResponse.ProtoReflect.Descriptor instead.
func (*SubmitGoalResponse) Descriptor() ([]byte, []int) {
	return file_orchestration_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitGoalResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *SubmitGoalResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ResumeFromInterruptRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	GoalUuid string                 `protobuf:"bytes,1,opt,name=goal_uuid,json=goalUuid,proto3" json:"goal_uuid,omitempty"`
	Decision string                 `protobuf:"bytes,2,opt,name=decision,proto3" json:"decision,omitempty"` // "approve" | "revise" | "reject"
	Feedback string                 `protobuf:"bytes,3,opt,name=feedback,proto3" json:"feedback,omitempty"` // free text for revise/steer (optional)
	// Edited review JSON (Flow A) the human cosigned, if any. Opaque to the worker.
	EditedPayloadJson string `protobuf:"bytes,4,opt,name=edited_payload_json,json=editedPayloadJson,proto3" json:"edited_payload_json,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ResumeFromInterruptRequest) Reset() {
	*x = ResumeFromInterruptRequest{}
	mi := &file_orchestration_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeFromInterruptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeFromInterruptRequest) ProtoMessage() {}

func (x *ResumeFromInterruptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestration_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeFromInterruptRequest.ProtoReflect.Descriptor instead.
func (*ResumeFromInterruptRequest) Descriptor() ([]byte, []int) {
	return file_orchestration_proto_rawDescGZIP(), []int{2}
}

func (x *ResumeFromInterruptRequest) GetGoalUuid() string {
	if x != nil {
		return x.GoalUuid
	}
	return ""
}

func (x *ResumeFromInterruptRequest) GetDecision() string {
	if x != nil {
		return x.Decision
	}
	return ""
}

func (x *ResumeFromInterruptRequest) GetFeedback() string {
	if x != nil {
		return x.Feedback
	}
	return ""
}

func (x *ResumeFromInterruptRequest) GetEditedPayloadJson() string {
	if x != nil {
		return x.EditedPayloadJson
	}
	return ""
}

type ResumeFromInterruptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeFromInterruptResponse) Reset() {
	*x = ResumeFromInterruptResponse{}
	mi := &file_orchestration_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeFromInterruptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeFromInterruptResponse) ProtoMessage() {}

func (x *ResumeFromInterruptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestration_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeFromInterruptResponse.ProtoReflect.Descriptor instead.
func (*ResumeFromInterruptResponse) Descriptor() ([]byte, []int) {
	return file_orchestration_proto_rawDescGZIP(), []int{3}
}

func (x *ResumeFromInterruptResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *ResumeFromInterruptResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CancelGoalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GoalUuid      string                 `protobuf:"bytes,1,opt,name=goal_uuid,json=goalUuid,proto3" json:"goal_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelGoalRequest) Reset() {
	*x = CancelGoalRequest{}
	mi := &file_orchestration_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelGoalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelGoalRequest) ProtoMessage() {}

func (x *CancelGoalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestration_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelGoalRequest.ProtoReflect.Descriptor instead.
func (*CancelGoalRequest) Descriptor() ([]byte, []int) {
	return file_orchestration_proto_rawDescGZIP(), []int{4}
}

func (x *CancelGoalRequest) GetGoalUuid() string {
	if x != nil {
		return x.GoalUuid
	}
	return ""
}

type CancelGoalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cancelled     bool                   `protobuf:"varint,1,opt,name=cancelled,proto3" json:"cancelled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelGoalResponse) Reset() {
	*x = CancelGoalResponse{}
	mi := &file_orchestration_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelGoalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelGoalResponse) ProtoMessage() {}

func (x *CancelGoalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestration_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelGoalResponse.ProtoReflect.Descriptor instead.
func (*CancelGoalResponse) Descriptor() ([]byte, []int) {
	return file_orchestration_proto_rawDescGZIP(), []int{5}
}

func (x *CancelGoalResponse) GetCancelled() bool {
	if x != nil {
		return x.Cancelled
	}
	return false
}

// ── Identity messages ─────────────────────────────────────────────────────────
type VerifyCapabilityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       int64                  `protobuf:"varint,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	ToolName      string                 `protobuf:"bytes,2,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyCapabilityRequest) Reset() {
	*x = VerifyCapabilityRequest{}
	mi := &file_orchestration_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyCapabilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyCapabilityRequest) ProtoMessage() {}

func (x *VerifyCapabilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestration_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyCapabilityRequest.ProtoReflect.Descriptor instead.
func (*VerifyCapabilityRequest) Descriptor() ([]byte, []int) {
	return file_orchestration_proto_rawDescGZIP(), []int{6}
}

func (x *VerifyCapabilityRequest) GetAgentId() int64 {
	if x != nil {
		return x.AgentId
	}
	return 0
}

func (x *VerifyCapabilityRequest) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

type VerifyCapabilityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allowed       bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyCapabilityResponse) Reset() {
	*x = VerifyCapabilityResponse{}
	mi := &file_orchestration_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyCapabilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyCapabilityResponse) ProtoMessage() {}

func (x *VerifyCapabilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestration_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyCapabilityResponse.ProtoReflect.Descriptor instead.
func (*VerifyCapabilityResponse) Descriptor() ([]byte, []int) {
	return file_orchestration_proto_rawDescGZIP(), []int{7}
}

func (x *VerifyCapabilityResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *VerifyCapabilityResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type GetUserOAuthTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserOAuthTokenRequest) Reset() {
	*x = GetUserOAuthTokenRequest{}
	mi := &file_orchestration_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserOAuthTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserOAuthTokenRequest) ProtoMessage() {}

func (x *GetUserOAuthTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestration_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserOAuthTokenRequest.ProtoReflect.Descriptor instead.
func (*GetUserOAuthTokenRequest) Descriptor() ([]byte, []int) {
	return file_orchestration_proto_rawDescGZIP(), []int{8}
}

func (x *GetUserOAuthTokenRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetUserOAuthTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OauthToken    string                 `protobuf:"bytes,1,opt,name=oauth_token,json=oauthToken,proto3" json:"oauth_token,omitempty"` // plaintext, decrypted in cosign-api memory
	GithubLogin   string                 `protobuf:"bytes,2,opt,name=github_login,json=githubLogin,proto3" json:"github_login,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserOAuthTokenResponse) Reset() {
	*x = GetUserOAuthTokenResponse{}
	mi := &file_orchestration_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserOAuthTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserOAuthTokenResponse) ProtoMessage() {}

func (x *GetUserOAuthTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestration_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserOAuthTokenResponse.ProtoReflect.Descriptor instead.
func (*GetUserOAuthTokenResponse) Descriptor() ([]byte, []int) {
	return file_orchestration_proto_rawDescGZIP(), []int{9}
}

func (x *GetUserOAuthTokenResponse) GetOauthToken() string {
	if x != nil {
		return x.OauthToken
	}
	return ""
}

func (x *GetUserOAuthTokenResponse) GetGithubLogin() string {
	if x != nil {
		return x.GithubLogin
	}
	return ""
}

type EmitAuditLogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActorType     string                 `protobuf:"bytes,1,opt,name=actor_type,json=actorType,proto3" json:"actor_type,omitempty"` // "user" | "agent" | "system"
	ActorId       int64                  `protobuf:"varint,2,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	EventType     string                 `protobuf:"bytes,3,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	GoalUuid      string                 `protobuf:"bytes,4,opt,name=goal_uuid,json=goalUuid,proto3" json:"goal_uuid,omitempty"`
	PayloadJson   string                 `protobuf:"bytes,5,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmitAuditLogRequest) Reset() {
	*x = EmitAuditLogRequest{}
	mi := &file_orchestration_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmitAuditLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmitAuditLogRequest) ProtoMessage() {}

func (x *EmitAuditLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestration_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmitAuditLogRequest.ProtoReflect.Descriptor instead.
func (*EmitAuditLogRequest) Descriptor() ([]byte, []int) {
	return file_orchestration_proto_rawDescGZIP(), []int{10}
}

func (x *EmitAuditLogRequest) GetActorType() string {
	if x != nil {
		return x.ActorType
	}
	return ""
}

func (x *EmitAuditLogRequest) GetActorId() int64 {
	if x != nil {
		return x.ActorId
	}
	return 0
}

func (x *EmitAuditLogRequest) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *EmitAuditLogRequest) GetGoalUuid() string {
	if x != nil {
		return x.GoalUuid
	}
	return ""
}

func (x *EmitAuditLogRequest) GetPayloadJson() string {
	if x != nil {
		return x.PayloadJson
	}
	return ""
}

type EmitAuditLogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmitAuditLogResponse) Reset() {
	*x = EmitAuditLogResponse{}
	mi := &file_orchestration_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmitAuditLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmitAuditLogResponse) ProtoMessage() {}

func (x *EmitAuditLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestration_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmitAuditLogResponse.ProtoReflect.Descriptor instead.
func (*EmitAuditLogResponse) Descriptor() ([]byte, []int) {
	return file_orchestration_proto_rawDescGZIP(), []int{11}
}

func (x *EmitAuditLogResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type GetUserLLMSettingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserLLMSettingsRequest) Reset() {
	*x = GetUserLLMSettingsRequest{}
	mi := &file_orchestration_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserLLMSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserLLMSettingsRequest) ProtoMessage() {}

func (x *GetUserLLMSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestration_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserLLMSettingsRequest.ProtoReflect.Descriptor instead.
func (*GetUserLLMSettingsRequest) Descriptor() ([]byte, []int) {
	return file_orchestration_proto_rawDescGZIP(), []int{12}
}

func (x *GetUserLLMSettingsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetUserLLMSettingsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// routing_json: { "<role|tool>": {"provider":..,"model":..} } as a JSON string.
	RoutingJson string `protobuf:"bytes,1,opt,name=routing_json,json=routingJson,proto3" json:"routing_json,omitempty"`
	// provider -> decrypted API key, for providers the user supplied a key for.
	ProviderKeys  map[string]string `protobuf:"bytes,2,rep,name=provider_keys,json=providerKeys,proto3" json:"provider_keys,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserLLMSettingsResponse) Reset() {
	*x = GetUserLLMSettingsResponse{}
	mi := &file_orchestration_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserLLMSettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserLLMSettingsResponse) ProtoMessage() {}

func (x *GetUserLLMSettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestration_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserLLMSettingsResponse.ProtoReflect.Descriptor instead.
func (*GetUserLLMSettingsResponse) Descriptor() ([]byte, []int) {
	return file_orchestration_proto_rawDescGZIP(), []int{13}
}

func (x *GetUserLLMSettingsResponse) GetRoutingJson() string {
	if x != nil {
		return x.RoutingJson
	}
	return ""
}

func (x *GetUserLLMSettingsResponse) GetProviderKeys() map[string]string {
	if x != nil {
		return x.ProviderKeys
	}
	return nil
}

var File_orchestration_proto protoreflect.FileDescriptor

const file_orchestration_proto_rawDesc = "" +
	"\n" +
	"\x13orchestration.proto\x12\x17cosign.orchestration.v1\"0\n" +
	"\x11SubmitGoalRequest\x12\x1b\n" +
	"\tgoal_uuid\x18\x01 \x01(\tR\bgoalUuid\"J\n" +
	"\x12SubmitGoalResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xa1\x01\n" +
	"\x1aResumeFromInterruptRequest\x12\x1b\n" +
	"\tgoal_uuid\x18\x01 \x01(\tR\bgoalUuid\x12\x1a\n" +
	"\bdecision\x18\x02 \x01(\tR\bdecision\x12\x1a\n" +
	"\bfeedback\x18\x03 \x01(\tR\bfeedback\x12.\n" +
	"\x13edited_payload_json\x18\x04 \x01(\tR\x11editedPayloadJson\"S\n" +
	"\x1bResumeFromInterruptResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"0\n" +
	"\x11CancelGoalRequest\x12\x1b\n" +
	"\tgoal_uuid\x18\x01 \x01(\tR\bgoalUuid\"2\n" +
	"\x12CancelGoalResponse\x12\x1c\n" +
	"\tcancelled\x18\x01 \x01(\bR\tcancelled\"Q\n" +
	"\x17VerifyCapabilityRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\x03R\aagentId\x12\x1b\n" +
	"\ttool_name\x18\x02 \x01(\tR\btoolName\"L\n" +
	"\x18VerifyCapabilityResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"3\n" +
	"\x18GetUserOAuthTokenRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"_\n" +
	"\x19GetUserOAuthTokenResponse\x12\x1f\n" +
	"\voauth_token\x18\x01 \x01(\tR\n" +
	"oauthToken\x12!\n" +
	"\fgithub_login\x18\x02 \x01(\tR\vgithubLogin\"\xae\x01\n" +
	"\x13EmitAuditLogRequest\x12\x1d\n" +
	"\n" +
	"actor_type\x18\x01 \x01(\tR\tactorType\x12\x19\n" +
	"\bactor_id\x18\x02 \x01(\x03R\aactorId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x03 \x01(\tR\teventType\x12\x1b\n" +
	"\tgoal_uuid\x18\x04 \x01(\tR\bgoalUuid\x12!\n" +
	"\fpayload_json\x18\x05 \x01(\tR\vpayloadJson\"&\n" +
	"\x14EmitAuditLogResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"4\n" +
	"\x19GetUserLLMSettingsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"\xec\x01\n" +
	"\x1aGetUserLLMSettingsResponse\x12!\n" +
	"\frouting_json\x18\x01 \x01(\tR\vroutingJson\x12j\n" +
	"\rprovider_keys\x18\x02 \x03(\v2E.cosign.orchestration.v1.GetUserLLMSettingsResponse.ProviderKeysEntryR\fproviderKeys\x1a?\n" +
	"\x11ProviderKeysEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xe7\x02\n" +
	"\x14OrchestrationService\x12e\n" +
	"\n" +
	"SubmitGoal\x12*.cosign.orchestration.v1.SubmitGoalRequest\x1a+.cosign.orchestration.v1.SubmitGoalResponse\x12\x80\x01\n" +
	"\x13ResumeFromInterrupt\x123.cosign.orchestration.v1.ResumeFromInterruptRequest\x1a4.cosign.orchestration.v1.ResumeFromInterruptResponse\x12e\n" +
	"\n" +
	"CancelGoal\x12*.cosign.orchestration.v1.CancelGoalRequest\x1a+.cosign.orchestration.v1.CancelGoalResponse2\xf2\x03\n" +
	"\x0fIdentityService\x12w\n" +
	"\x10VerifyCapability\x120.cosign.orchestration.v1.VerifyCapabilityRequest\x1a1.cosign.orchestration.v1.VerifyCapabilityResponse\x12z\n" +
	"\x11GetUserOAuthToken\x121.cosign.orchestration.v1.GetUserOAuthTokenRequest\x1a2.cosign.orchestration.v1.GetUserOAuthTokenResponse\x12k\n" +
	"\fEmitAuditLog\x12,.cosign.orchestration.v1.EmitAuditLogRequest\x1a-.cosign.orchestration.v1.EmitAuditLogResponse\x12}\n" +
	"\x12GetUserLLMSettings\x122.cosign.orchestration.v1.GetUserLLMSettingsRequest\x1a3.cosign.orchestration.v1.GetUserLLMSettingsResponseBCZAgithub.com/tensor-bloom/cosign/services/cosign-api/internal/pb;pbb\x06proto3"

var (
	file_orchestration_proto_rawDescOnce sync.Once
	file_orchestration_proto_rawDescData []byte
)

func file_orchestration_proto_rawDescGZIP() []byte {
	file_orchestration_proto_rawDescOnce.Do(func() {
		file_orchestration_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_orchestration_proto_rawDesc), len(file_orchestration_proto_rawDesc)))
	})
	return file_orchestration_proto_rawDescData
}

var file_orchestration_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_orchestration_proto_goTypes = []any{
	(*SubmitGoalRequest)(nil),           // 0: cosign.orchestration.v1.SubmitGoalRequest
	(*SubmitGoalResponse)(nil),          // 1: cosign.orchestration.v1.SubmitGoalResponse
	(*ResumeFromInterruptRequest)(nil),  // 2: cosign.orchestration.v1.ResumeFromInterruptRequest
	(*ResumeFromInterruptResponse)(nil), // 3: cosign.orchestration.v1.ResumeFromInterruptResponse
	(*CancelGoalRequest)(nil),           // 4: cosign.orchestration.v1.CancelGoalRequest
	(*CancelGoalResponse)(nil),          // 5: cosign.orchestration.v1.CancelGoalResponse
	(*VerifyCapabilityRequest)(nil),     // 6: cosign.orchestration.v1.VerifyCapabilityRequest
	(*VerifyCapabilityResponse)(nil),    // 7: cosign.orchestration.v1.VerifyCapabilityResponse
	(*GetUserOAuthTokenRequest)(nil),    // 8: cosign.orchestration.v1.GetUserOAuthTokenRequest
	(*GetUserOAuthTokenResponse)(nil),   // 9: cosign.orchestration.v1.GetUserOAuthTokenResponse
	(*EmitAuditLogRequest)(nil),         // 10: cosign.orchestration.v1.EmitAuditLogRequest
	(*EmitAuditLogResponse)(nil),        // 11: cosign.orchestration.v1.EmitAuditLogResponse
	(*GetUserLLMSettingsRequest)(nil),   // 12: cosign.orchestration.v1.GetUserLLMSettingsRequest
	(*GetUserLLMSettingsResponse)(nil),  // 13: cosign.orchestration.v1.GetUserLLMSettingsResponse
	nil,                                 // 14: cosign.orchestration.v1.GetUserLLMSettingsResponse.ProviderKeysEntry
}
var file_orchestration_proto_depIdxs = []int32{
	14, // 0: cosign.orchestration.v1.GetUserLLMSettingsResponse.provider_keys:type_name -> cosign.orchestration.v1.GetUserLLMSettingsResponse.ProviderKeysEntry
	0,  // 1: cosign.orchestration.v1.OrchestrationService.SubmitGoal:input_type -> cosign.orchestration.v1.SubmitGoalRequest
	2,  // 2: cosign.orchestration.v1.OrchestrationService.ResumeFromInterrupt:input_type -> cosign.orchestration.v1.ResumeFromInterruptRequest
	4,  // 3: cosign.orchestration.v1.OrchestrationService.CancelGoal:input_type -> cosign.orchestration.v1.CancelGoalRequest
	6,  // 4: cosign.orchestration.v1.IdentityService.VerifyCapability:input_type -> cosign.orchestration.v1.VerifyCapabilityRequest
	8,  // 5: cosign.orchestration.v1.IdentityService.GetUserOAuthToken:input_type -> cosign.orchestration.v1.GetUserOAuthTokenRequest
	10, // 6: cosign.orchestration.v1.IdentityService.EmitAuditLog:input_type -> cosign.orchestration.v1.EmitAuditLogRequest
	12, // 7: cosign.orchestration.v1.IdentityService.GetUserLLMSettings:input_type -> cosign.orchestration.v1.GetUserLLMSettingsRequest
	1,  // 8: cosign.orchestration.v1.OrchestrationService.SubmitGoal:output_type -> cosign.orchestration.v1.SubmitGoalResponse
	3,  // 9: cosign.orchestration.v1.OrchestrationService.ResumeFromInterrupt:output_type -> cosign.orchestration.v1.ResumeFromInterruptResponse
	5,  // 10: cosign.orchestration.v1.OrchestrationService.CancelGoal:output_type -> cosign.orchestration.v1.CancelGoalResponse
	7,  // 11: cosign.orchestration.v1.IdentityService.VerifyCapability:output_type -> cosign.orchestration.v1.VerifyCapabilityResponse
	9,  // 12: cosign.orchestration.v1.IdentityService.GetUserOAuthToken:output_type -> cosign.orchestration.v1.GetUserOAuthTokenResponse
	11, // 13: cosign.orchestration.v1.IdentityService.EmitAuditLog:output_type -> cosign.orchestration.v1.EmitAuditLogResponse
	13, // 14: cosign.orchestration.v1.IdentityService.GetUserLLMSettings:output_type -> cosign.orchestration.v1.GetUserLLMSettingsResponse
	8,  // [8:15] is the sub-list for method output_type
	1,  // [1:8] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_orchestration_proto_init() }
func file_orchestration_proto_init() {
	if File_orchestration_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orchestration_proto_rawDesc), len(file_orchestration_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_orchestration_proto_goTypes,
		DependencyIndexes: file_orchestration_proto_depIdxs,
		MessageInfos:      file_orchestration_proto_msgTypes,
	}.Build()
	File_orchestration_proto = out.File
	file_orchestration_proto_goTypes = nil
	file_orchestration_proto_depIdxs = nil
}
