// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: orchestration.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OrchestrationService_SubmitGoal_FullMethodName          = "/cosign.orchestration.v1.OrchestrationService/SubmitGoal"
	OrchestrationService_ResumeFromInterrupt_FullMethodName = "/cosign.orchestration.v1.OrchestrationService/ResumeFromInterrupt"
	OrchestrationService_CancelGoal_FullMethodName          = "/cosign.orchestration.v1.OrchestrationService/CancelGoal"
)

// OrchestrationServiceClient is the client API for OrchestrationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ── OrchestrationService ──────────────────────────────────────────────────────
// Implemented by cosign-worker (Python). Called by cosign-api (Go) to drive
// agent runs. See ARCHITECTURE §3 (Data Flow).
type OrchestrationServiceClient interface {
	// Start a goal: load it, build the LangGraph thread, run until the first
	// HITL gate or completion. Returns immediately (work continues async; the
	// browser follows progress over SSE).
	SubmitGoal(ctx context.Context, in *SubmitGoalRequest, opts ...grpc.CallOption) (*SubmitGoalResponse, error)
	// Resume a goal suspended at a HITL gate after the human cosigns / revises /
	// rejects.
	ResumeFromInterrupt(ctx context.Context, in *ResumeFromInterruptRequest, opts ...grpc.CallOption) (*ResumeFromInterruptResponse, error)
	// Cancel a running goal and clean up its sandbox.
	CancelGoal(ctx context.Context, in *CancelGoalRequest, opts ...grpc.CallOption) (*CancelGoalResponse, error)
}

type orchestrationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrchestrationServiceClient(cc grpc.ClientConnInterface) OrchestrationServiceClient {
	return &orchestrationServiceClient{cc}
}

func (c *orchestrationServiceClient) SubmitGoal(ctx context.Context, in *SubmitGoalRequest, opts ...grpc.CallOption) (*SubmitGoalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitGoalResponse)
	err := c.cc.Invoke(ctx, OrchestrationService_SubmitGoal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestrationServiceClient) ResumeFromInterrupt(ctx context.Context, in *ResumeFromInterruptRequest, opts ...grpc.CallOption) (*ResumeFromInterruptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResumeFromInterruptResponse)
	err := c.cc.Invoke(ctx, OrchestrationService_ResumeFromInterrupt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestrationServiceClient) CancelGoal(ctx context.Context, in *CancelGoalRequest, opts ...grpc.CallOption) (*CancelGoalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelGoalResponse)
	err := c.cc.Invoke(ctx, OrchestrationService_CancelGoal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrchestrationServiceServer is the server API for OrchestrationService service.
// All implementations must embed UnimplementedOrchestrationServiceServer
// for forward compatibility.
//
// ── OrchestrationService ──────────────────────────────────────────────────────
// Implemented by cosign-worker (Python). Called by cosign-api (Go) to drive
// agent runs. See ARCHITECTURE §3 (Data Flow).
type OrchestrationServiceServer interface {
	// Start a goal: load it, build the LangGraph thread, run until the first
	// HITL gate or completion. Returns immediately (work continues async; the
	// browser follows progress over SSE).
	SubmitGoal(context.Context, *SubmitGoalRequest) (*SubmitGoalResponse, error)
	// Resume a goal suspended at a HITL gate after the human cosigns / revises /
	// rejects.
	ResumeFromInterrupt(context.Context, *ResumeFromInterruptRequest) (*ResumeFromInterruptResponse, error)
	// Cancel a running goal and clean up its sandbox.
	CancelGoal(context.Context, *CancelGoalRequest) (*CancelGoalResponse, error)
	mustEmbedUnimplementedOrchestrationServiceServer()
}

// UnimplementedOrchestrationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrchestrationServiceServer struct{}

func (UnimplementedOrchestrationServiceServer) SubmitGoal(context.Context, *SubmitGoalRequest) (*SubmitGoalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitGoal not implemented")
}
func (UnimplementedOrchestrationServiceServer) ResumeFromInterrupt(context.Context, *ResumeFromInterruptRequest) (*ResumeFromInterruptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResumeFromInterrupt not implemented")
}
func (UnimplementedOrchestrationServiceServer) CancelGoal(context.Context, *CancelGoalRequest) (*CancelGoalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelGoal not implemented")
}
func (UnimplementedOrchestrationServiceServer) mustEmbedUnimplementedOrchestrationServiceServer() {}
func (UnimplementedOrchestrationServiceServer) testEmbeddedByValue()                              {}

// UnsafeOrchestrationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrchestrationServiceServer will
// result in compilation errors.
type UnsafeOrchestrationServiceServer interface {
	mustEmbedUnimplementedOrchestrationServiceServer()
}

func RegisterOrchestrationServiceServer(s grpc.ServiceRegistrar, srv OrchestrationServiceServer) {
	// If the following call panics, it indicates UnimplementedOrchestrationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrchestrationService_ServiceDesc, srv)
}

func _OrchestrationService_SubmitGoal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitGoalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestrationServiceServer).SubmitGoal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestrationService_SubmitGoal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestrationServiceServer).SubmitGoal(ctx, req.(*SubmitGoalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestrationService_ResumeFromInterrupt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResumeFromInterruptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestrationServiceServer).ResumeFromInterrupt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestrationService_ResumeFromInterrupt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestrationServiceServer).ResumeFromInterrupt(ctx, req.(*ResumeFromInterruptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestrationService_CancelGoal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelGoalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestrationServiceServer).CancelGoal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestrationService_CancelGoal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestrationServiceServer).CancelGoal(ctx, req.(*CancelGoalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OrchestrationService_ServiceDesc is the grpc.ServiceDesc for OrchestrationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrchestrationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cosign.orchestration.v1.OrchestrationService",
	HandlerType: (*OrchestrationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitGoal",
			Handler:    _OrchestrationService_SubmitGoal_Handler,
		},
		{
			MethodName: "ResumeFromInterrupt",
			Handler:    _OrchestrationService_ResumeFromInterrupt_Handler,
		},
		{
			MethodName: "CancelGoal",
			Handler:    _OrchestrationService_CancelGoal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "orchestration.proto",
}

const (
	IdentityService_VerifyCapability_FullMethodName   = "/cosign.orchestration.v1.IdentityService/VerifyCapability"
	IdentityService_GetUserOAuthToken_FullMethodName  = "/cosign.orchestration.v1.IdentityService/GetUserOAuthToken"
	IdentityService_EmitAuditLog_FullMethodName       = "/cosign.orchestration.v1.IdentityService/EmitAuditLog"
	IdentityService_GetUserLLMSettings_FullMethodName = "/cosign.orchestration.v1.IdentityService/GetUserLLMSettings"
)

// IdentityServiceClient is the client API for IdentityService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ── IdentityService ───────────────────────────────────────────────────────────
// Implemented by cosign-api (Go). Called by cosign-worker (Python) to check
// agent capabilities, fetch the invoking user's OAuth token, and emit audit
// events. See ARCHITECTURE §9.2 + §7.1.
type IdentityServiceClient interface {
	// Per-tool capability gate. Every tool call checks this before executing.
	VerifyCapability(ctx context.Context, in *VerifyCapabilityRequest, opts ...grpc.CallOption) (*VerifyCapabilityResponse, error)
	// Decrypt + return the user's GitHub OAuth token so the worker can act AS the
	// user (never a bot). Used at goal start and before GitHub writes.
	GetUserOAuthToken(ctx context.Context, in *GetUserOAuthTokenRequest, opts ...grpc.CallOption) (*GetUserOAuthTokenResponse, error)
	// Append an audit-log row (tool calls, state changes).
	EmitAuditLog(ctx context.Context, in *EmitAuditLogRequest, opts ...grpc.CallOption) (*EmitAuditLogResponse, error)
	// Return the user's per-tool routing overrides + their decrypted provider API
	// keys (BYO). Same trust boundary as GetUserOAuthToken: decrypted in cosign-api
	// memory, handed to the worker, never logged.
	GetUserLLMSettings(ctx context.Context, in *GetUserLLMSettingsRequest, opts ...grpc.CallOption) (*GetUserLLMSettingsResponse, error)
}

type identityServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIdentityServiceClient(cc grpc.ClientConnInterface) IdentityServiceClient {
	return &identityServiceClient{cc}
}

func (c *identityServiceClient) VerifyCapability(ctx context.Context, in *VerifyCapabilityRequest, opts ...grpc.CallOption) (*VerifyCapabilityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyCapabilityResponse)
	err := c.cc.Invoke(ctx, IdentityService_VerifyCapability_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) GetUserOAuthToken(ctx context.Context, in *GetUserOAuthTokenRequest, opts ...grpc.CallOption) (*GetUserOAuthTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserOAuthTokenResponse)
	err := c.cc.Invoke(ctx, IdentityService_GetUserOAuthToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) EmitAuditLog(ctx context.Context, in *EmitAuditLogRequest, opts ...grpc.CallOption) (*EmitAuditLogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmitAuditLogResponse)
	err := c.cc.Invoke(ctx, IdentityService_EmitAuditLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) GetUserLLMSettings(ctx context.Context, in *GetUserLLMSettingsRequest, opts ...grpc.CallOption) (*GetUserLLMSettingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserLLMSettingsResponse)
	err := c.cc.Invoke(ctx, IdentityService_GetUserLLMSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IdentityServiceServer is the server API for IdentityService service.
// All implementations must embed UnimplementedIdentityServiceServer
// for forward compatibility.
//
// ── IdentityService ───────────────────────────────────────────────────────────
// Implemented by cosign-api (Go). Called by cosign-worker (Python) to check
// agent capabilities, fetch the invoking user's OAuth token, and emit audit
// events. See ARCHITECTURE §9.2 + §7.1.
type IdentityServiceServer interface {
	// Per-tool capability gate. Every tool call checks this before executing.
	VerifyCapability(context.Context, *VerifyCapabilityRequest) (*VerifyCapabilityResponse, error)
	// Decrypt + return the user's GitHub OAuth token so the worker can act AS the
	// user (never a bot). Used at goal start and before GitHub writes.
	GetUserOAuthToken(context.Context, *GetUserOAuthTokenRequest) (*GetUserOAuthTokenResponse, error)
	// Append an audit-log row (tool calls, state changes).
	EmitAuditLog(context.Context, *EmitAuditLogRequest) (*EmitAuditLogResponse, error)
	// Return the user's per-tool routing overrides + their decrypted provider API
	// keys (BYO). Same trust boundary as GetUserOAuthToken: decrypted in cosign-api
	// memory, handed to the worker, never logged.
	GetUserLLMSettings(context.Context, *GetUserLLMSettingsRequest) (*GetUserLLMSettingsResponse, error)
	mustEmbedUnimplementedIdentityServiceServer()
}

// UnimplementedIdentityServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIdentityServiceServer struct{}

func (UnimplementedIdentityServiceServer) VerifyCapability(context.Context, *VerifyCapabilityRequest) (*VerifyCapabilityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyCapability not implemented")
}
func (UnimplementedIdentityServiceServer) GetUserOAuthToken(context.Context, *GetUserOAuthTokenRequest) (*GetUserOAuthTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserOAuthToken not implemented")
}
func (UnimplementedIdentityServiceServer) EmitAuditLog(context.Context, *EmitAuditLogRequest) (*EmitAuditLogResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EmitAuditLog not implemented")
}
func (UnimplementedIdentityServiceServer) GetUserLLMSettings(context.Context, *GetUserLLMSettingsRequest) (*GetUserLLMSettingsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserLLMSettings not implemented")
}
func (UnimplementedIdentityServiceServer) mustEmbedUnimplementedIdentityServiceServer() {}
func (UnimplementedIdentityServiceServer) testEmbeddedByValue()                         {}

// UnsafeIdentityServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IdentityServiceServer will
// result in compilation errors.
type UnsafeIdentityServiceServer interface {
	mustEmbedUnimplementedIdentityServiceServer()
}

func RegisterIdentityServiceServer(s grpc.ServiceRegistrar, srv IdentityServiceServer) {
	// If the following call panics, it indicates UnimplementedIdentityServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IdentityService_ServiceDesc, srv)
}

func _IdentityService_VerifyCapability_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyCapabilityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).VerifyCapability(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_VerifyCapability_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).VerifyCapability(ctx, req.(*VerifyCapabilityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_GetUserOAuthToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserOAuthTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).GetUserOAuthToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_GetUserOAuthToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).GetUserOAuthToken(ctx, req.(*GetUserOAuthTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_EmitAuditLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmitAuditLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).EmitAuditLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_EmitAuditLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).EmitAuditLog(ctx, req.(*EmitAuditLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_GetUserLLMSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserLLMSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).GetUserLLMSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_GetUserLLMSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).GetUserLLMSettings(ctx, req.(*GetUserLLMSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IdentityService_ServiceDesc is the grpc.ServiceDesc for IdentityService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IdentityService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cosign.orchestration.v1.IdentityService",
	HandlerType: (*IdentityServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "VerifyCapability",
			Handler:    _IdentityService_VerifyCapability_Handler,
		},
		{
			MethodName: "GetUserOAuthToken",
			Handler:    _IdentityService_GetUserOAuthToken_Handler,
		},
		{
			MethodName: "EmitAuditLog",
			Handler:    _IdentityService_EmitAuditLog_Handler,
		},
		{
			MethodName: "GetUserLLMSettings",
			Handler:    _IdentityService_GetUserLLMSettings_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "orchestration.proto",
}
