# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import orchestration_pb2 as orchestration__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in orchestration_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OrchestrationServiceStub:
    """── OrchestrationService ──────────────────────────────────────────────────────
    Implemented by cosign-worker (Python). Called by cosign-api (Go) to drive
    agent runs. See ARCHITECTURE §3 (Data Flow).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitGoal = channel.unary_unary(
                '/cosign.orchestration.v1.OrchestrationService/SubmitGoal',
                request_serializer=orchestration__pb2.SubmitGoalRequest.SerializeToString,
                response_deserializer=orchestration__pb2.SubmitGoalResponse.FromString,
                _registered_method=True)
        self.ResumeFromInterrupt = channel.unary_unary(
                '/cosign.orchestration.v1.OrchestrationService/ResumeFromInterrupt',
                request_serializer=orchestration__pb2.ResumeFromInterruptRequest.SerializeToString,
                response_deserializer=orchestration__pb2.ResumeFromInterruptResponse.FromString,
                _registered_method=True)
        self.CancelGoal = channel.unary_unary(
                '/cosign.orchestration.v1.OrchestrationService/CancelGoal',
                request_serializer=orchestration__pb2.CancelGoalRequest.SerializeToString,
                response_deserializer=orchestration__pb2.CancelGoalResponse.FromString,
                _registered_method=True)


class OrchestrationServiceServicer:
    """── OrchestrationService ──────────────────────────────────────────────────────
    Implemented by cosign-worker (Python). Called by cosign-api (Go) to drive
    agent runs. See ARCHITECTURE §3 (Data Flow).
    """

    def SubmitGoal(self, request, context):
        """Start a goal: load it, build the LangGraph thread, run until the first
        HITL gate or completion. Returns immediately (work continues async; the
        browser follows progress over SSE).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResumeFromInterrupt(self, request, context):
        """Resume a goal suspended at a HITL gate after the human cosigns / revises /
        rejects.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelGoal(self, request, context):
        """Cancel a running goal and clean up its sandbox.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrchestrationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitGoal': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitGoal,
                    request_deserializer=orchestration__pb2.SubmitGoalRequest.FromString,
                    response_serializer=orchestration__pb2.SubmitGoalResponse.SerializeToString,
            ),
            'ResumeFromInterrupt': grpc.unary_unary_rpc_method_handler(
                    servicer.ResumeFromInterrupt,
                    request_deserializer=orchestration__pb2.ResumeFromInterruptRequest.FromString,
                    response_serializer=orchestration__pb2.ResumeFromInterruptResponse.SerializeToString,
            ),
            'CancelGoal': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelGoal,
                    request_deserializer=orchestration__pb2.CancelGoalRequest.FromString,
                    response_serializer=orchestration__pb2.CancelGoalResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cosign.orchestration.v1.OrchestrationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cosign.orchestration.v1.OrchestrationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OrchestrationService:
    """── OrchestrationService ──────────────────────────────────────────────────────
    Implemented by cosign-worker (Python). Called by cosign-api (Go) to drive
    agent runs. See ARCHITECTURE §3 (Data Flow).
    """

    @staticmethod
    def SubmitGoal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cosign.orchestration.v1.OrchestrationService/SubmitGoal',
            orchestration__pb2.SubmitGoalRequest.SerializeToString,
            orchestration__pb2.SubmitGoalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResumeFromInterrupt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cosign.orchestration.v1.OrchestrationService/ResumeFromInterrupt',
            orchestration__pb2.ResumeFromInterruptRequest.SerializeToString,
            orchestration__pb2.ResumeFromInterruptResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelGoal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cosign.orchestration.v1.OrchestrationService/CancelGoal',
            orchestration__pb2.CancelGoalRequest.SerializeToString,
            orchestration__pb2.CancelGoalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class IdentityServiceStub:
    """── IdentityService ───────────────────────────────────────────────────────────
    Implemented by cosign-api (Go). Called by cosign-worker (Python) to check
    agent capabilities, fetch the invoking user's OAuth token, and emit audit
    events. See ARCHITECTURE §9.2 + §7.1.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.VerifyCapability = channel.unary_unary(
                '/cosign.orchestration.v1.IdentityService/VerifyCapability',
                request_serializer=orchestration__pb2.VerifyCapabilityRequest.SerializeToString,
                response_deserializer=orchestration__pb2.VerifyCapabilityResponse.FromString,
                _registered_method=True)
        self.GetUserOAuthToken = channel.unary_unary(
                '/cosign.orchestration.v1.IdentityService/GetUserOAuthToken',
                request_serializer=orchestration__pb2.GetUserOAuthTokenRequest.SerializeToString,
                response_deserializer=orchestration__pb2.GetUserOAuthTokenResponse.FromString,
                _registered_method=True)
        self.EmitAuditLog = channel.unary_unary(
                '/cosign.orchestration.v1.IdentityService/EmitAuditLog',
                request_serializer=orchestration__pb2.EmitAuditLogRequest.SerializeToString,
                response_deserializer=orchestration__pb2.EmitAuditLogResponse.FromString,
                _registered_method=True)
        self.GetUserLLMSettings = channel.unary_unary(
                '/cosign.orchestration.v1.IdentityService/GetUserLLMSettings',
                request_serializer=orchestration__pb2.GetUserLLMSettingsRequest.SerializeToString,
                response_deserializer=orchestration__pb2.GetUserLLMSettingsResponse.FromString,
                _registered_method=True)


class IdentityServiceServicer:
    """── IdentityService ───────────────────────────────────────────────────────────
    Implemented by cosign-api (Go). Called by cosign-worker (Python) to check
    agent capabilities, fetch the invoking user's OAuth token, and emit audit
    events. See ARCHITECTURE §9.2 + §7.1.
    """

    def VerifyCapability(self, request, context):
        """Per-tool capability gate. Every tool call checks this before executing.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserOAuthToken(self, request, context):
        """Decrypt + return the user's GitHub OAuth token so the worker can act AS the
        user (never a bot). Used at goal start and before GitHub writes.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EmitAuditLog(self, request, context):
        """Append an audit-log row (tool calls, state changes).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserLLMSettings(self, request, context):
        """Return the user's per-tool routing overrides + their decrypted provider API
        keys (BYO). Same trust boundary as GetUserOAuthToken: decrypted in cosign-api
        memory, handed to the worker, never logged.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IdentityServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'VerifyCapability': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyCapability,
                    request_deserializer=orchestration__pb2.VerifyCapabilityRequest.FromString,
                    response_serializer=orchestration__pb2.VerifyCapabilityResponse.SerializeToString,
            ),
            'GetUserOAuthToken': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserOAuthToken,
                    request_deserializer=orchestration__pb2.GetUserOAuthTokenRequest.FromString,
                    response_serializer=orchestration__pb2.GetUserOAuthTokenResponse.SerializeToString,
            ),
            'EmitAuditLog': grpc.unary_unary_rpc_method_handler(
                    servicer.EmitAuditLog,
                    request_deserializer=orchestration__pb2.EmitAuditLogRequest.FromString,
                    response_serializer=orchestration__pb2.EmitAuditLogResponse.SerializeToString,
            ),
            'GetUserLLMSettings': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserLLMSettings,
                    request_deserializer=orchestration__pb2.GetUserLLMSettingsRequest.FromString,
                    response_serializer=orchestration__pb2.GetUserLLMSettingsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cosign.orchestration.v1.IdentityService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cosign.orchestration.v1.IdentityService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class IdentityService:
    """── IdentityService ───────────────────────────────────────────────────────────
    Implemented by cosign-api (Go). Called by cosign-worker (Python) to check
    agent capabilities, fetch the invoking user's OAuth token, and emit audit
    events. See ARCHITECTURE §9.2 + §7.1.
    """

    @staticmethod
    def VerifyCapability(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cosign.orchestration.v1.IdentityService/VerifyCapability',
            orchestration__pb2.VerifyCapabilityRequest.SerializeToString,
            orchestration__pb2.VerifyCapabilityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserOAuthToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cosign.orchestration.v1.IdentityService/GetUserOAuthToken',
            orchestration__pb2.GetUserOAuthTokenRequest.SerializeToString,
            orchestration__pb2.GetUserOAuthTokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EmitAuditLog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cosign.orchestration.v1.IdentityService/EmitAuditLog',
            orchestration__pb2.EmitAuditLogRequest.SerializeToString,
            orchestration__pb2.EmitAuditLogResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserLLMSettings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cosign.orchestration.v1.IdentityService/GetUserLLMSettings',
            orchestration__pb2.GetUserLLMSettingsRequest.SerializeToString,
            orchestration__pb2.GetUserLLMSettingsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
